install.packages("survival")
library(survival)
data(cancer)
str(cancer)
View(cancer)
sfit <- survfit(Surv(time, status)~sex, data=cancer)
summary(sfit)
install.packager("survminer")
library(survminer)
s <- Surv(cancer$time, cancer$status)
sfit <- (survfit(Surv(time, status)~sex, data=cancer))survfit(Surv(time, status)~sex, data=cancer)
plot(sfit)
ggsurvplot(sfit)
ggsurvplot(sfit, risk.table = TRUE, legend.labs=c("Male", "Female"))
sfit <- survfit(Surv(time, status)~inst, data=cancer)
ggsurvplot(sfit)
coxph(formula=Surv(time, status)~sex, data=cancer)