sample(1:10)
sample(1:10, size = 5)
sample(c(0,1), 10, replace = TRUE)
outcome <- c("Head","Tail")
sample(outcome, size=1)
sample(outcome, size=100, replace=TRUE)
sample(AirPassengers, size=10)
sample.int(20, 12)
dnorm(0)
dnorm(0,mean=3,sd=5)
curve(dnorm,-3,3)
pnorm(1.5)
pnorm(1.5, lower.tail=FALSE)
curve(pnorm(x), -3,3)
qnorm(0.5)
qnorm(pnorm(0))
set.seed(50)
x = rnorm(100,mean=3,sd=5)
hist(x)
set.seed(50)
y = runif(100,0,5)
hist(y)
shapiro.test(x)
data(mtcars)
range(mtcars$mpg)
length(mtcars$mpg)
mean(mtcars$mpg)
median(mtcars$mpg)
sd(mtcars$mpg)
var(mtcars$mpg)
sd(mtcars$mpg) ^ 2
IQR(mtcars$mpg)
quantile(mtcars$mpg,0.67)
max(mtcars$mpg)
min(mtcars$mpg)
cummax(mtcars$mpg)
cummin(mtcars$mpg)
summary(mtcars)
table(mtcars$cyl)
stem(mtcars$mpg)
library(ggplot2)
qplot(mtcars$mpg, binwidth=2)
pie(table(mtcars$cyl), main="Number of Cylinders")
mode = function(x) {
   temp = table(x)
   names(temp)[temp == max(temp)]
   }
x = c(1,2,3,3,3,4,4,5,5,5,6)
mode(x)
cov(mtcars[1:3])
cor(mtcars[1:3])
library(reshape2)
qplot(x=Var1, y=Var2, data=melt(cor(mtcars[1:3])), fill=value, geom="tile")
binom.test(x=92, n=315, p=1/6)
boxplot(mtcars$mpg, mtcars$mpg[mtcars$am==0], ylab = "mpg", names=c("overall","automobile"))
abline(h=mean(mtcars$mpg),lwd=2, col="red")
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")
mpg.mu = mean(mtcars$mpg)
pg_am = mtcars$mpg[mtcars$am == 0]
t.test(mpg_am,mu = mpg.mu)
box-plot(mtcars$mpg~mtcars$am,ylab='mpg',names=c('automatic','manual'))
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")
abline(h=mean(mtcars$mpg[mtcars$am==1]),lwd=2, col="red")
t.test(mtcars$mpg~mtcars$am)
data = data.frame(marks=sample(40:100, 60, re-place=TRUE),division=c(rep('A',30), rep('B',30)))
head(data)
boxplot(data$marks, data$marks[data$division=='A'], ylab="Marks", names=c("All Marks", "Div A"))
abline(h=mean(data$marks), lwd=2, col="red")
abline(h=mean(data$marks[data$division=='A']), lwd=2, col="blue")
meanmarks = mean(data$marks)
marksA = data$marks[data$division=='A']
t.test(marksA, mu = meanmarks)
boxplot(data$marks~data$division, ylab="Marks", names=c("A", "B"))
abline(h=mean(data$marks[data$division=="A"]), lwd=2, col="red")
abline(h=mean(data$marks[data$division=="B"]), lwd=2, col="blue")
t.test(data$marks~data$division)
x = rnorm(50)
ks.test(x,"pnorm")
set.seed(3)
x = runif(n=20, min=0, max=20)
y = runif(n=20, min=0, max=20)
plot(ecdf(x), do.points = FALSE, verticals=T, xlim=c(0, 20))
lines(ecdf(y), lty=3, do.points = FALSE, verticals=T)
ks.test(x,y)
g1 = sample(50:100, 30, replace=TRUE)
g2 = sample(50:100, 30, replace=TRUE)
plot.ecdf(g1, verticals=TRUE, do.points=FALSE, col="red")
lines(ecdf(g2), verticals=TRUE, do.points=FALSE, col="blue")
ks.test(g1,g2)
box-plot(mtcars$mpg~mtcars$am,ylab='mpg',names=c('automatic','manual'))
wilcox.test(mpg ~ am, data=mtcars)
ftable = table(mtcars$am, mtcars$gear)
ftable
mosaicplot(ftable, main="Number of Forward Gears Within Au-tomatic and Manual Cars", color = TRUE)
chisq.test(ftable)
library(MASS)
str(survey)
tbl = table(survey$Smoke, survey$Exer) 
tbl
chisq.test(tbl)
box-plot(mtcars$mpg~factor(mtcars$gear),xlab='gear',ylab='mpg')
library(ggplot2)
ggplot(mtcars,aes(mtcars$mpg,mtcars$gear, col-or=mtcars$gear))+geom_point()
oneway.test(mtcars$mpg~factor(mtcars$gear))
mtcars.aov = aov(mtcars$mpg ~ as.factor(mtcars$gear))
summary(mtcars.aov)
model.tables(mtcars.aov, "means")
mtcars_posthoc =TukeyHSD(mtcars.aov)
mtcars_posthoc
`as.factor(mtcars$gear)`
par(mfrow=c(1,2))
box-plot(mtcars$mpg~mtcars$gear,subset=(mtcars$am==0),xlab='gear', ylab = "mpg",main='automatic')
box-plot(mtcars$mpg~mtcars$gear,subset=(mtcars$am==1),xlab='gear', ylab = "mpg", main='manual')
boxplot(mtcars$mpg~factor(mtcars$gear)* fac-tor(mtcars$am),xlab='gear * transmission', ylab = "mpg",main='Boxplot of mpg by gear * transmission')
interaction.plot(mtcars$gear, mtcars$am, mtcars$mpg, type="b", col=c(1:3),leg.bty="o", leg.bg="beige", lwd=2, pch=c(18,24,22), xlab="Number of Gears", ylab="Mean Miles Per Gallon", main="Interaction Plot")
mpg_anova2 = aov(mtcars$mpg~factor(mtcars$gear)*factor(mtcars$am))
summary(mpg_anova2) 
TukeyHSD(mpg_anova2)
`factor(mtcars$gear)`
`factor(mtcars$am)`
par(mfrow=c(1,2))
plot(TukeyHSD(mpg_anova2))
