class(AirPassengers)
start(AirPassengers)
end(AirPassengers)
summary(AirPassengers)
my_vector = sample(2500:4000, 72, replace=T)
my_series = ts(my_vector, start=c(2011,1), end=c(2016,12), frequency = 12) 
my_series
plot(my_series)
plot(AirPassengers)
cycle(AirPassengers)
aggregate(AirPassengers)
plot(aggregate(AirPassengers))
boxplot(AirPassengers~cycle(AirPassengers))
install.packages("forecast")
require(forecast)
forecast(my_series, 4)
f = HoltWinters(my_series)
forecast(f,4)
forecast(AirPassengers, 4)
head(my_series)
tail(my_series)
tail(my_series, 20)
head(my_series,5)
require(xts)
first(my_series)
last(my_series)
first(my_series, "3 months")
first(my_series, "3 years")
last(my_series, "3 months")
last(my_series, "3 years")
window(my_series, start=c(2009,1), end=c(2013,12))
my_series1 = ts(my_vector1, start=c(2011,1), end=c(2013,12), frequency = 4)
my_series1[c(2,5,10,13)]=NA
my_series1
mean(my_series1, na.rm = TRUE)
my_series1[is.na(my_series1)]=706
my_series1
ma(my_series, order=10)
library(forecast)
t = ets(AirPassengers)
t
plot(t)
val = forecast(t)
plot(val)
sales = sample(400:10000, 72, replace= TRUE)
sales
my_newseries = ts(sales, start=c(2011,1), end=c(2016,12), frequen-cy = 12)
my_newseries
lag.plot(AirPassenger, lags=10)
lag.plot(newseries, lags=10)
acf(AirPassengers)
acf(my_newseries)